### ISSUE TITLE
Hey a lil issue not to big.

### ISSUE THREAD

**Issue by CherriVirus** [pylyf/NetWorm#3]
Hello! I am wondering how this works in full detail? such as you open a prompt for it? I'm a bit of a newbie at this. I'd love some feedback I find this project very interesting to me 

Much love 

Cherri

**Comment by maximousblk** [comment]
Did you install all the plugins?

**Comment by maximousblk** [comment]
This needs a little readme update

**Comment by pylyf** [comment]
Hi @CherriVirus! For the worm to work, you need to install all the python libraries that are imported. Then, you need to edit the code a bit. In the `main()` function ( worm.py ) you have to choose and call all the functions that you want to use on the victim's computer. 

This project does indeed require updates and I will work on them. @maximousblk 

Let me know if you have any questions.

Cheers,
pylyf
