### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by CrackerB1A7E** [pylyf/NetWorm#4]
Idk if I don't know how to work it or because it doesn't work

**Comment by maximousblk** [comment]
As clearly stated, this is an incomplete project and doesn't work well enough. you might need to fiddle around a bit to make it work.

**Comment by CrackerB1A7E** [comment]
i cant program sorry

În sâm., 29 feb. 2020 la 11:22, Maximous Black <notifications@github.com> a
scris:
