### ISSUE TITLE
I am reciving an error in the python console wil it affect my code and if it does how can i fix it?

### ISSUE THREAD

**Issue by Saw8888** [pylyf/NetWorm#6]
I am reciving this error: WARNING: Could not import all necessary Npcap functions. You may need to upgrade to the latest version from https://npcap.org. Resorting to connect() mode -- Nmap may not function completely

Thank you for helping

**Comment by pylyf** [comment]
The Warning says that your npcap is not up to date. Try updating it. (pip install python-nmap, ..)
I can't tell how it affects the code because the error doesn't say which functions aren't imported.
