### ISSUE TITLE
i cant use it

### ISSUE THREAD

**Issue by kaance** [pylyf/NetWorm#7]
C:\Program Files (x86)\Nmap>worm.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Nmap\worm.py", line 7, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'``

what do i do wrong?

**Comment by pylyf** [comment]
Hi, 
Your error says that the **python-nmap** library is not installed on your machine.

Please try running this command in your console:
`pip install python-nmap`

If that doesn´t help, check out the python-nmap library documentation.
https://pypi.org/project/python-nmap/

**Comment by nomad1420** [comment]
> C:\Program Files (x86)\Nmap>worm.py Traceback (most recent call last): File "C:\Program Files (x86)\Nmap\worm.py", line 7, in import nmap ModuleNotFoundError: No module named 'nmap'``
> 
> what do i do wrong?

dostum ulaş bana
